# Generated by Django 4.0.4 on 2022-04-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_phone_numer_informationsetup_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_name', models.CharField(max_length=10, verbose_name='pseudo_name')),
                ('comment', models.TextField(verbose_name='comment')),
                ('state', models.CharField(choices=[('visible', 'Visible'), ('invisible', 'Invisible')], default='visible', max_length=9, verbose_name='visible')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('invisible', 'Invisible')], default='visible', max_length=9, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('invisible', 'Invisible')], default='visible', max_length=9, verbose_name='visibility'),
        ),
    ]
