# Generated by Django 4.0.4 on 2022-04-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_alter_article_status_alter_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pseudo_name',
            new_name='owner_pseudo_name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='informationsetup',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='github url link'),
        ),
        migrations.AlterField(
            model_name='informationsetup',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='linkedin profile link'),
        ),
        migrations.AlterField(
            model_name='informationsetup',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='twitter url link'),
        ),
    ]
