# Generated by Django 4.0.4 on 2022-04-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_pseudo_name_comment_owner_pseudo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsetup',
            name='cv_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='pdf CV'),
        ),
    ]
